### ISSUE TITLE
Inaccurate Top PP Play

### ISSUE THREAD

**Issue by kacphur** [osuAkatsuki/hanayo#34]
If you look on the website, it says that RyuK has the Top score for pp on Vanilla. That score is 1007pp, but the actual score has had a buff in pp with 1029pp.
![e38e0b04-8d09-4f9e-91f1-ac7a8cca496c](https://user-images.githubusercontent.com/90797543/204361506-4683ed67-ce95-4232-8356-b18682618f7f.png)
![cf352aaa-d95d-4bcd-93e5-c83d44037fcd](https://user-images.githubusercontent.com/90797543/204361519-1d6b803f-8388-485c-9eca-0ae7071b768c.png)

**Comment by cmyui** [comment]
Ah nice catch, looks like redis values were not updated after the pp recalculation was performed

https://github.com/osuAkatsuki/hanayo/blob/master/web/templates/homepage.html#L137-L139

**Comment by cmyui** [comment]
We should probably make some RPC which we can use from recalc scripts in the future to run a job to recalc these

**Comment by lenforiee** [comment]
it was our cron issue, has been already fixed however as cmyui said we need better approach for it
