### ISSUE TITLE
Fix badges not being able to be applied

### ISSUE THREAD

**Issue by cmyui** [osuAkatsuki/hanayo#4]

**Comment by qewc** [comment]
just upload the badge bruh

**Comment by qewc** [comment]
-_-

**Comment by ilytt** [comment]
This is an API issue if I remember correctly.

**Comment by cmyui** [comment]
1. It is not only badges, but that whole page is cursed.
2. It's related to privileges in some sort: use the page fine.

Definitely large on the TODO list, although not knowing go whatsoever makes it a rather difficult hurdle to jump over.

**Comment by ilytt** [comment]
This weekend I could probably PR a change to fix it.

**Comment by cmyui** [comment]
It has been narrowed down to being an issue with not having premium.

**Comment by ilytt** [comment]
why would badges be a premium thing?

**Comment by cmyui** [comment]
It’s not just the badges, it’s everything on that page

**Comment by cmyui** [comment]
Fixed!
